# Generated by Django 5.2 on 2026-01-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('season', models.CharField(max_length=9)),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('nba_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPropLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(max_length=50)),
                ('period', models.IntegerField()),
                ('line', models.FloatField()),
                ('odds_over', models.IntegerField()),
                ('odds_under', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.bookmaker')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.player')),
            ],
            options={
                'unique_together': {('player', 'game', 'bookmaker', 'prop_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('prediction_timestamp', models.DateTimeField()),
                ('prob_over', models.FloatField()),
                ('recommendation', models.CharField(max_length=50)),
                ('prop_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.playerpropline')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nba_betting.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='nba_betting.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nba_betting.team'),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(help_text='0=Full, 1-4=Quarter')),
                ('pts', models.IntegerField(default=0)),
                ('reb', models.IntegerField(default=0)),
                ('ast', models.IntegerField(default=0)),
                ('min', models.FloatField(default=0.0)),
                ('fga', models.IntegerField(default=0)),
                ('fgm', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.team')),
            ],
            options={
                'unique_together': {('player', 'game', 'period')},
            },
        ),
    ]
